---
engines:
  rubocop:
    enabled: true
    exclude_fingerprints:
      - c78d54034662278a4268b723e32aec63
  golint:
    enabled: false
  gofmt:
    enabled: false
  eslint:
    enabled: false
  csslint:
    enabled: false
  reek:
    enabled: true
