AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'bin/*'
    - 'docker/*'
    - 'Guardfile'
    - 'basquiat.gemspec'
Metrics/BlockLength:
  Exclude:
    - !ruby/regexp /^spec.*/

Metrics/LineLength:
  Max: 119

Layout/AlignHash:
  EnforcedHashRocketStyle: key

Style/Documentation:
  Enabled: false
