AllCops:
  Exclude:
    - 'bin/*'
    - 'docker/*'
    - 'Guardfile'
    - 'basquiat.gemspec'
Metrics/LineLength:
  Max: 109

Style/AlignHash:
  EnforcedHashRocketStyle: table

Style/Documentation:
  Enabled: false
