AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'bin/*'
    - 'docker/*'
    - 'Guardfile'
    - 'basquiat.gemspec'
Metrics/LineLength:
  Max: 119

Style/AlignHash:
  EnforcedHashRocketStyle: table

Style/Documentation:
  Enabled: false
