basquiat:
  build: docker
  command: /basquiat/docker/guard_start.sh
  volumes:
    - ./:/basquiat
  links:
    - rabbitmq
  tty: true
  stdin_open: true

rabbitmq:
  image: mereghost/rabbitmq:latest
